(()=>{'use strict';
const screens=[...document.querySelectorAll('.screen')],$=id=>document.getElementById(id),state={kind:'',food:'',day:0,time:'',year:0,month:0};
const show=n=>{screens.forEach((s,i)=>s.classList.toggle('active',i===n));scrollTo(0,0)};
function hearts(n=20){const a=['💗','💕','💖','♥️','✨'];for(let i=0;i<n;i++){const e=document.createElement('span');e.className='heart';e.textContent=a[Math.floor(Math.random()*a.length)];e.style.left=(8+Math.random()*84)+'vw';e.style.top=(58+Math.random()*28)+'vh';e.style.setProperty('--x',(Math.random()*180-90)+'px');e.style.animationDelay=(Math.random()*.2)+'s';document.body.append(e);setTimeout(()=>e.remove(),1700)}}
const no=$('noBtn'),zone=$('buttonZone');let tries=0,lastMove=0;
function runNo(ev){if(ev){ev.preventDefault();ev.stopPropagation()}const now=Date.now();if(now-lastMove<55)return;lastMove=now;tries++;const z=zone.getBoundingClientRect(),w=no.offsetWidth||106,h=no.offsetHeight||56;no.style.right='auto';no.style.left=Math.random()*Math.max(0,z.width-w-4)+'px';no.style.top=Math.random()*Math.max(0,z.height-h-4)+'px';const scale=Math.max(.34,1-tries*.085);no.style.transform=`scale(${scale}) rotate(${Math.random()*18-9}deg)`;no.textContent=tries>8?'ну хватит':'Нет'}
['pointerenter','pointerdown','click'].forEach(x=>no.addEventListener(x,runNo));
$('yesBtn').onclick=()=>{hearts(35);setTimeout(()=>show(1),500)};
document.querySelectorAll('.date-option').forEach(b=>b.onclick=()=>{state.kind=b.dataset.choice;hearts(10);setTimeout(()=>show(2),220)});
const foodModal=$('foodModal');document.querySelectorAll('.food').forEach(b=>b.onclick=()=>{state.food=b.textContent.trim();foodModal.classList.add('show');hearts(12)});$('foodOk').onclick=()=>{foodModal.classList.remove('show');show(3)};
function calendar(){const now=new Date();state.year=now.getFullYear();state.month=now.getMonth();const names=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];$('monthTitle').textContent=names[state.month]+' '+state.year;const box=$('days');box.innerHTML='';const offset=(new Date(state.year,state.month,1).getDay()+6)%7,total=new Date(state.year,state.month+1,0).getDate();for(let i=0;i<offset;i++){const x=document.createElement('span');x.className='day blank';box.append(x)}for(let d=1;d<=total;d++){const b=document.createElement('button');b.className='day';b.type='button';b.textContent=d;b.onclick=()=>{box.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.day=d;check()};box.append(b)}}
const time=$('time'),next=$('dateContinue');function check(){next.disabled=!(state.day&&time.value)}time.oninput=()=>{state.time=time.value;check()};next.onclick=()=>{if(!next.disabled){$('timeModal').classList.add('show');hearts(15)}};$('timeOk').onclick=()=>{$('timeModal').classList.remove('show');const date=String(state.day).padStart(2,'0')+'.'+String(state.month+1).padStart(2,'0')+'.'+state.year;$('summary').textContent=`Выбрано: ${state.kind}, ${date} в ${state.time}. Но Никита всё равно всё решит 😼`;hearts(35);setTimeout(()=>show(4),420)};
$('restart').onclick=()=>{Object.assign(state,{kind:'',food:'',day:0,time:''});time.value='';next.disabled=true;tries=0;no.removeAttribute('style');no.textContent='Нет';calendar();show(0)};
foodModal.onclick=e=>{if(e.target===foodModal)foodModal.classList.remove('show')};$('timeModal').onclick=e=>{if(e.target===$('timeModal'))$('timeModal').classList.remove('show')};calendar();
})();